version: '3.0'

services:
  app:
    image: ${DOCKER_REGISTRY}/intermittency:latest
    build:
      context: .

  timescaledb:
    image: timescaledev/timescaledb-ha:pg12-latest
    ports:
      - 5432:5432/tcp
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  selenium:
    #image: seleniarm/standalone-firefox:4.3.0-20220709
    image: selenium/standalone-firefox:4.26.0-20241101
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "5900:5900"
