# frozen_string_literal: true

require 'faraday/net_http_persistent'
require 'zip'
require 'fastest_csv'

module AemoNem
  class Base
    include SemanticLogger::Loggable
    include CliMixin2::Loop

    def self.source_id
      'aemo'
    end

    def self.select_file?(url)
      url =~ /.zip$/i
    end

    def self.each
      logger.info("Fetch #{self::URL}")
      res = Faraday.get(self::URL)

      res.body.split(/<br>/).each do |row|
        m = row.match(/(.*)\s+\d+\s+<A HREF="(.*?)"/)
        next unless m
        next unless select_file?(m[2])

        url = self::URL_BASE + m[2]
        time = Time.strptime(m[1].strip, self::INDEX_TIME_FORMAT)
        time = self::TZ.local_to_utc(time)

        if DataFile.where(updated_at: time...Float::INFINITY, path: File.basename(url), source: source_id).exists?
          logger.debug "already processed #{File.basename(url)}"
          next
        end
        yield url
      end

      nil
    end

    def initialize
      @datafiles = []
      @faraday = Faraday.new do |f|
        f.adapter :net_http_persistent
        f.response :raise_error
      end
    end

    HTTP_DATE_FORMAT = '%a, %d %b %Y %H:%M:%S GMT'
    def add(input)
      add_url(input)
    end

    def add_url(url)
      last_modified = DataFile.last_modified(url, self.class.source_id)
      res = logger.benchmark_info("Fetch #{url}") do
        @faraday.get(url) do |req|
          req.headers['If-Modified-Since'] = last_modified if last_modified
        end
      end
      if res.status == 304
        logger.warn "304 Not Modified #{url}"
        return self
      end

      last_modified = Time.strptime(res.headers['Last-Modified'], HTTP_DATE_FORMAT)
      add_buffer(res.body, url, last_modified)

      self
    end

    def add_file(path)
      file = File.open(path)
      add_buffer(file.read, path, file.mtime)

      self
    end

    def add_buffer(data, name, date)
      if name =~ /\.zip$/
        Zip::File.open_buffer(data) do |zip|
          raise 'FIXME' unless zip.count == 1

          zip_entry = zip.entries.first
          data = zip_entry.get_input_stream.read
          # name = zip_entry.name
          date = zip_entry.mtime
        end
      end
      parse_filename!(name)

      @datafiles << { path: File.basename(name), updated_at: date, source: self.class.source_id }
      add_buffer2(data)

      self
    end

    def add_buffer2(data)
      add_csv(FastestCSV.parse(data, row_sep: "\r\n"))
    end

    def done!
      DataFile.upsert_all(@datafiles, unique_by: %i[source path])
      datafiles = @datafiles.map { |datafile| datafile[:path] }.join ', '
      logger.info "done! #{datafiles}"
    end

    ROW_TIME_FORMAT = '%Y/%m/%d %H:%M:%S'
    def parse_time(s)
      return @last_t if @last_s == s

      @last_s = s
      @last_t = self.class::TZ.local_to_utc(Time.strptime(s, self.class::ROW_TIME_FORMAT))
    end

    TZ = TZInfo::Timezone.get('Etc/GMT-10')
    URL_BASE = 'https://nemweb.com.au'
    INDEX_TIME_FORMAT = '%A, %B %d, %Y %l:%M %p'
    FILE_FORMAT = '%Y%m%d%H%M'

    def parse_filename!(name)
      name = File.basename(name)
      m = name.match(self.class::FILE_MATCHER)
      raise ArgumentError, "invalid filename: #{name} doesn't match #{self.class::FILE_MATCHER}" unless m

      from = Time.strptime(m[1], self.class::FILE_FORMAT)
      from = TZ.local_to_utc(from)
      to = from + 5.minutes
      @from = [from, @from].compact.min
      @to = [to, @to].compact.max
    end
  end

  class Trading < Base
    include SemanticLogger::Loggable

    URL = 'https://nemweb.com.au/Reports/Current/TradingIS_Reports/'
    FILE_MATCHER = /PUBLIC_TRADINGIS_(\d{12})_/

    def initialize
      super
      @r = []
    end

    def add_csv(csv)
      csv.select { |row| row[0..2] == %w[D TRADING PRICE] }.each do |row|
        # I
        # TRADING
        # PRICE
        # 3
        # SETTLEMENTDATE
        time = parse_time(row[4])
        # RUNNO
        # REGIONID
        country = row[6]
        # PERIODID
        # RRP
        value = row[8].to_f * 100
        # EEP
        # INVALIDFLAG
        # LASTCHANGED
        # ROP
        # RAISE6SECRRP
        # RAISE6SECROP
        # RAISE60SECRRP
        # RAISE60SECROP
        # RAISE5MINRRP
        # RAISE5MINROP
        # RAISEREGRRP
        # RAISEREGROP
        # LOWER6SECRRP
        # LOWER6SECROP
        # LOWER60SECRRP
        # LOWER60SECROP
        # LOWER5MINRRP
        # LOWER5MINROP
        # LOWERREGRRP
        # LOWERREGROP
        # RAISE1SECRRP
        # RAISE1SECROP
        # LOWER1SECRRP
        # LOWER1SECROP
        # PRICE_STATUS

        @r << { time:, country:, value: }
      end
    end

    def done!
      Out::Price.run(@r, @from, @to, self.class.source_id)
      super
    end
  end

  class Dispatch < Base
    include SemanticLogger::Loggable

    URL = 'https://nemweb.com.au/Reports/Current/DispatchIS_Reports/'
    FILE_MATCHER = /PUBLIC_DISPATCHIS_(\d{12})_/

    # Generated by scripts/units-transmission-metadata.rb
    MAPPINGS = {
      'N-Q-MNSP1' => %w[NSW1 QLD1],
      'N-Q-MNSP1-2' => %w[NSW1 QLD1],
      'NSW1-QLD1' => %w[NSW1 QLD1],
      'NSW1-QLD1-2' => %w[NSW1 QLD1],
      'T-V-MNSP1' => %w[TAS1 VIC1],
      'T-V-MNSP1-2' => %w[TAS1 VIC1],
      'V-S-MNSP1' => %w[VIC1 SA1],
      'V-S-MNSP1-2' => %w[VIC1 SA1],
      'V-SA' => %w[VIC1 SA1],
      'V-SA-2' => %w[VIC1 SA1],
      'VIC1-NSW1' => %w[VIC1 NSW1],
      'VIC1-NSW1-2' => %w[VIC1 NSW1]
    }

    def initialize
      super
      @r_tran = {}
      @r_gen = {}
    end

    def add_csv(csv)
      # from_area_id = Area.find_by source: self.class.source_id, code: 'TAS1'
      # to_area_id = Area.find_by source: self.class.source_id, code: 'VIC1'
      csv.select { |row| row[0..2] == %w[D DISPATCH INTERCONNECTORRES] }.each do |row|
        # 0:I
        # 1:DISPATCH
        # 2:INTERCONNECTORRES
        # 3:3
        # 4:SETTLEMENTDATE
        time = parse_time(row[4])
        # 5:RUNNO
        # 6:INTERCONNECTORID
        from_area, to_area = MAPPINGS[row[6]]
        # 7:DISPATCHINTERVAL
        # 8:INTERVENTION
        # 9:METEREDMWFLOW
        value = -(row[9].to_f * 1000).to_i
        # MWFLOW
        # MWLOSSES
        # MARGINALVALUE
        # VIOLATIONDEGREE
        # LASTCHANGED
        # EXPORTLIMIT
        # IMPORTLIMIT
        # MARGINALLOSS
        # EXPORTGENCONID
        # IMPORTGENCONID
        # FCASEXPORTLIMIT
        # FCASIMPORTLIMIT
        # LOCAL_PRICE_ADJUSTMENT_EXPORT
        # LOCALLY_CONSTRAINED_EXPORT
        # LOCAL_PRICE_ADJUSTMENT_IMPORT
        # LOCALLY_CONSTRAINED_IMPORT

        k = [time, from_area, to_area]
        @r_tran[k] ||= { time:, from_area:, to_area:, value: 0 }
        @r_tran[k][:value] += value
      end
      # require 'pry' ; binding.pry

      csv.select { |row| row[0..2] == %w[D DISPATCH REGIONSUM] }.each do |row|
        # I
        # DISPATCH
        # REGIONSUM
        # 7
        # SETTLEMENTDATE
        time = parse_time(row[4])
        # RUNNO
        # REGIONID
        country = row[6]
        # DISPATCHINTERVAL
        # INTERVENTION
        # TOTALDEMAND
        # ##value = row[9]
        # AVAILABLEGENERATION
        # AVAILABLELOAD
        # DEMANDFORECAST
        # DISPATCHABLEGENERATION
        # DISPATCHABLELOAD
        # NETINTERCHANGE
        # EXCESSGENERATION
        # LOWER5MINDISPATCH
        # LOWER5MINIMPORT
        # LOWER5MINLOCALDISPATCH
        # LOWER5MINLOCALPRICE
        # LOWER5MINLOCALREQ
        # LOWER5MINPRICE
        # LOWER5MINREQ
        # LOWER5MINSUPPLYPRICE
        # LOWER60SECDISPATCH
        # LOWER60SECIMPORT
        # LOWER60SECLOCALDISPATCH
        # LOWER60SECLOCALPRICE
        # LOWER60SECLOCALREQ
        # LOWER60SECPRICE
        # LOWER60SECREQ
        # LOWER60SECSUPPLYPRICE
        # LOWER6SECDISPATCH
        # LOWER6SECIMPORT
        # LOWER6SECLOCALDISPATCH
        # LOWER6SECLOCALPRICE
        # LOWER6SECLOCALREQ
        # LOWER6SECPRICE
        # LOWER6SECREQ
        # LOWER6SECSUPPLYPRICE
        # RAISE5MINDISPATCH
        # RAISE5MINIMPORT
        # RAISE5MINLOCALDISPATCH
        # RAISE5MINLOCALPRICE
        # RAISE5MINLOCALREQ
        # RAISE5MINPRICE
        # RAISE5MINREQ
        # RAISE5MINSUPPLYPRICE
        # RAISE60SECDISPATCH
        # RAISE60SECIMPORT
        # RAISE60SECLOCALDISPATCH
        # RAISE60SECLOCALPRICE
        # RAISE60SECLOCALREQ
        # RAISE60SECPRICE
        # RAISE60SECREQ
        # RAISE60SECSUPPLYPRICE
        # RAISE6SECDISPATCH
        # RAISE6SECIMPORT
        # RAISE6SECLOCALDISPATCH
        # RAISE6SECLOCALPRICE
        # RAISE6SECLOCALREQ
        # RAISE6SECPRICE
        # RAISE6SECREQ
        # RAISE6SECSUPPLYPRICE
        # AGGEGATEDISPATCHERROR
        # AGGREGATEDISPATCHERROR
        # LASTCHANGED
        # INITIALSUPPLY
        # CLEAREDSUPPLY
        # LOWERREGIMPORT
        # LOWERREGLOCALDISPATCH
        # LOWERREGLOCALREQ
        # LOWERREGREQ
        # RAISEREGIMPORT
        # RAISEREGLOCALDISPATCH
        # RAISEREGLOCALREQ
        # RAISEREGREQ
        # RAISE5MINLOCALVIOLATION
        # RAISEREGLOCALVIOLATION
        # RAISE60SECLOCALVIOLATION
        # RAISE6SECLOCALVIOLATION
        # LOWER5MINLOCALVIOLATION
        # LOWERREGLOCALVIOLATION
        # LOWER60SECLOCALVIOLATION
        # LOWER6SECLOCALVIOLATION
        # RAISE5MINVIOLATION
        # RAISEREGVIOLATION
        # RAISE60SECVIOLATION
        # RAISE6SECVIOLATION
        # LOWER5MINVIOLATION
        # LOWERREGVIOLATION
        # LOWER60SECVIOLATION
        # LOWER6SECVIOLATION
        # RAISE6SECACTUALAVAILABILITY
        # RAISE60SECACTUALAVAILABILITY
        # RAISE5MINACTUALAVAILABILITY
        # RAISEREGACTUALAVAILABILITY
        # LOWER6SECACTUALAVAILABILITY
        # LOWER60SECACTUALAVAILABILITY
        # LOWER5MINACTUALAVAILABILITY
        # LOWERREGACTUALAVAILABILITY
        # LORSURPLUS
        # LRCSURPLUS
        # TOTALINTERMITTENTGENERATION
        # DEMAND_AND_NONSCHEDGEN
        value = row[105].to_f * 1000
        # UIGF
        # SEMISCHEDULE_CLEAREDMW
        # SEMISCHEDULE_COMPLIANCEMW
        # SS_SOLAR_UIGF
        # SS_WIND_UIGF
        # SS_SOLAR_CLEAREDMW
        # SS_WIND_CLEAREDMW
        # SS_SOLAR_COMPLIANCEMW
        # SS_WIND_COMPLIANCEMW
        # WDR_INITIALMW
        # WDR_AVAILABLE
        # WDR_DISPATCHED
        # RAISE1SECLOCALDISPATCH
        # LOWER1SECLOCALDISPATCH
        # RAISE1SECACTUALAVAILABILITY
        # LOWER1SECACTUALAVAILABILITY
        # SS_SOLAR_AVAILABILITY
        # SS_WIND_AVAILABILITY
        k = [country, time]
        @r_gen[k] = { country:, time:, value: }
      end
      # require 'pry' ; binding.pry
    end

    def done!
      Out::Transmission.run(@r_tran.values, @from, @to, self.class.source_id)
      Out::Load.run(@r_gen.values, @from, @to, self.class.source_id)
      super
    end
  end

  class CauserPays < Base
    include SemanticLogger::Loggable

    URL = 'http://www.nemweb.com.au/Reports/Current/Causer_Pays/'
    FILE_MATCHER = /FCAS_(\d{12}).zip/
    # ELEMENTS_URL = 'http://www.nemweb.com.au/Reports/Current/Causer_Pays_Elements/'

    def initialize
      super
    end

    @@elements = false
    def self.elements
      return @@elements if @@elements

      url = 'http://www.nemweb.com.au/Reports/Current/Causer_Pays_Elements/Elements_FCAS_202402020950.csv'
      logger.info("Fetch #{url}")
      res = Faraday.get(url)

      csv = FastestCSV.parse(res.body, row_sep: "\r\n")
      @@elements = {}
      csv.each do |row|
        id = row[0].to_i
        element = row[1].strip
        next unless element =~ /^SUBSTN\./

        element.gsub!(/^SUBSTN\./, '')
        @@elements[id] = element
      end

      @@elements
    end

    ROW_TIME_FORMAT = '%Y-%m-%d %H:%M:%S'

    def initialize
      @r = []
    end

    @@units = {}
    def add_csv(csv)
      default_area_id = Area.where(type: 'country', source: self.class.source_id).pluck(:id).first
      default_production_type_id = ProductionType.where(name: 'other').pluck(:id).first

      logger.benchmark_info('parse csv') do
        csv.each do |row|
          time = parse_time(row[0])
          unit_internal_id = self.class.elements[row[1].to_i]
          next unless unit_internal_id

          unit = @@units[unit_internal_id]
          unit ||= ::Unit.find_by(hires_internal_id: unit_internal_id)
          unit ||= ::Unit
                   .create_with(area_id: default_area_id,
                                production_type_id: default_production_type_id)
                   .find_or_create_by!(internal_id: unit_internal_id)
          @@units[unit_internal_id] ||= unit

          unit_id = unit.id
          variable = row[2].to_i
          next unless variable == 2

          value = row[3].to_f * 1000

          @r << { time:, unit_id:, value: }
        end
      end
      # require 'pry' ; binding.pry
    end

    def done!
      Out::UnitHires.run(@r, @from, @to, self.class.source_id)
      super
    end
  end

  class Scada < Base
    include SemanticLogger::Loggable

    URL = 'https://nemweb.com.au/Reports/Current/Dispatch_SCADA/'
    FILE_MATCHER = /PUBLIC_DISPATCHSCADA_(\d{12})_/

    def initialize
      super
      @r = []
    end

    def add_file(path)
      unless @from
        name = File.basename(path)
        parse_filename!(name)
      end
      super
    end

    def self.clear_cache!
      @@units = {}
    end
    @@units = {}
    def add_csv(csv)
      default_area_id = Area.where(type: 'country', source: self.class.source_id).pluck(:id).first
      default_production_type_id = ProductionType.where(name: 'other').pluck(:id).first

      logger.benchmark_info('parse csv') do
        csv.select { |row| row[0..2] == %w[D DISPATCH UNIT_SCADA] }.each do |row|
          # I
          # DISPATCH
          # UNIT_SCADA
          # 1
          # SETTLEMENTDATE
          time = parse_time(row[4])
          # DUID
          unit_internal_id = row[5]
          unit = @@units[unit_internal_id] ||= ::Unit
                                               .create_with(area_id: default_area_id,
                                                            production_type_id: default_production_type_id)
                                               .find_or_create_by!(internal_id: unit_internal_id)
          unit_id = unit.id
          # SCADAVALUE
          value = row[6].to_f * 1000
          value = -value if %w[hydro_pumped_storage battery_charging].include? unit.production_type.name

          @r << { time:, unit_id:, value: }
        end
      end
    end

    def done!
      return if @r.empty?

      Out::Unit.run(@r, @from, @to, self.class.source_id)
      GenerationUnit.aggregate_to_generation(@from, @to, "a.source='aemo' AND a.code<>'WEM'")
      super
    end
  end

  class DuDetail < Base
    include SemanticLogger::Loggable

    def initialize
      super
      @r = {}
    end

    @@units = {}
    def add_csv(csv)
      logger.benchmark_info('parse csv') do
        headers = Hash[csv[1].each_with_index.to_a]
        csv.select { |row| row[0..2] == %w[D PARTICIPANT_REGISTRATION DUDETAIL] }.each do |row|
          # I
          # PARTICIPANT_REGISTRATION
          # DUDETAIL
          # 4
          # DUID
          unit_internal_id = row[headers['DUID']]
          unit_id = @@units[unit_internal_id] ||= Unit.where(internal_id: unit_internal_id).pluck(:id).first
          unless unit_id
            logger.warn("No unit #{unit_internal_id}")
            next
          end
          # EFFECTIVEDATE
          time = parse_time(row[headers['EFFECTIVEDATE']])
          # VERSIONNO
          # CONNECTIONPOINTID
          # VOLTLEVEL
          # REGISTEREDCAPACITY
          value = row[9].to_f * 1000
          # AGCCAPABILITY
          # DISPATCHTYPE
          # MAXCAPACITY
          # value2 = row[12]
          # STARTTYPE
          # NORMALLYONFLAG
          # PHYSICALDETAILSFLAG
          # SPINNINGRESERVEFLAG
          # AUTHORISEDBY
          # AUTHORISEDDATE
          # LASTCHANGED
          # INTERMITTENTFLAG
          # SEMISCHEDULE_FLAG
          # MAXRATEOFCHANGEUP
          # MAXRATEOFCHANGEDOWN
          # DISPATCHSUBTYPE
          # ADG_ID
          k = [unit_id, time]
          @r[k] = { unit_id:, time:, value: }
        end
      end
      # require 'pry' ; binding.pry
    end

    def done!
      Out::UnitCapacity.run(@r.values, @from, @to, self.class.source_id)
      super
    end
  end

  class RooftopPv < Base
    include SemanticLogger::Loggable

    URL = 'https://nemweb.com.au/Reports/Current/ROOFTOP_PV/ACTUAL/'
    FILE_MATCHER = /PUBLIC_ROOFTOP_PV_ACTUAL_MEASUREMENT_(\d{12}00)_/

    def initialize
      super
      @r = []
    end

    def self.select_file?(url)
      super && url =~ /PUBLIC_ROOFTOP_PV_ACTUAL_MEASUREMENT_/
    end

    def add_csv(csv)
      csv.select { |row| row[0..2] == %w[D ROOFTOP ACTUAL] && row[8] == 'MEASUREMENT' }.each do |row|
        # I
        # ROOFTOP
        # ACTUAL
        # 2
        # INTERVAL_DATETIME
        time = parse_time(row[4])
        # REGIONID
        country = row[5]
        # POWER
        value = row[6].to_f * 1000
        # QI
        # TYPE
        # LASTCHANGED
        next unless country =~ /1$/

        @r << { time:, country:, production_type: 'solar_rooftop', value: }
      end
    end

    def done!
      Out::Generation.run(@r, @from, @to, self.class.source_id)
      Generation.aggregate_rooftoppv_to_capture(@from, @to, "a.code <> 'WEM'")
      super
    end
  end
end
